---
functional:
  - требование 1 Пользователь должен иметь возможность создать игру.
  - требование 2 Пользователь должен иметь возможность выбрать свой Уровень.
  - требование 3 Пользователь должен иметь возможность выбрать тип игры (с ботом, с другом, с другими пользователями).
  - требование 4 Пользователь должен иметь возможность выбрать время игры.
  - требование 5 Пользователь должен иметь возможность выбрать задание.
  - требование 6 Пользователь должен иметь возможность писать код.
  - требование 7 Пользователь должен иметь возможность видеть код соперника.
  - требование 8 Пользователь должен иметь возможность проверить свой код.
  - требование 9 Пользователь должен иметь возможность зарегистрироваться на сайте.
non-functional:
  - требование 10 Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - требование 11 Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - требование 12 Сайт должен быть безопасным и защищать данные пользователя.
  - требование 13 Сайт должен быть удобным на мобильном устройстве.
  - требование 14 Сайт должен быть способен обрабатывать большое количество трафика.
implicit:
  - требование 15 Пользователь должен иметь возможность видеть таблицу лидеров. 
